version: "3.8"

services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT}:9000"        # S3 API
      - "${MINIO_CONSOLE_PORT}:9091"    # Console UI
    volumes:
      - "${MINIO_DATA}:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server /data --console-address ":9091"
